# 正式环境
profile: prod

server:
  port: 80


#MySQL
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/boot_manage?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: xxxx
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    hostName: xxxx
    port: 6379
    password: xxxx
    timeout: 5000
    pool:
      max-active: 9
      min-idle: 2
      max-idle: 9
      max-wait: -1